//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinDefendManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinDefendManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a @echo off
        ///::Windows Defender
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\MsSecFlt&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;4&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\SecurityHealthService&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;4&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\Sense&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;4&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\WdBoot&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;4&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\WdFilter&quot; /v &quot;Start&quot; /t REG_D [stringa troncata]&quot;;.
        /// </summary>
        internal static string DisableWD {
            get {
                return ResourceManager.GetString("DisableWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a @echo off
        ///::Windows Defender
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\MsSecFlt&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;0&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\SecurityHealthService&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;3&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\Sense&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;3&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\WdBoot&quot; /v &quot;Start&quot; /t REG_DWORD /d &quot;0&quot; /f &gt;NUL 2&gt;nul
        ///reg add &quot;HKLM\SYSTEM\ControlSet001\Services\WdFilter&quot; /v &quot;Start&quot; /t REG_D [stringa troncata]&quot;;.
        /// </summary>
        internal static string EnableWD {
            get {
                return ResourceManager.GetString("EnableWD", resourceCulture);
            }
        }
    }
}
